[build]
  command = "yarn build:fast && yarn website:build"
  publish = "packages/website/public"

[[redirects]]
  from = "https://reakit.netlify.com/*"
  to = "https://reakit.io/:splat"
  status = 301
  force = true
