name: 🧩 Example request
description: Suggest a use case for a component.
labels: ["examples"]
body:
  - type: textarea
    attributes:
      label: Description
      description: >
        Describe the use case. **Make sure you include screenshots, videos
        and/or code sandboxes**, otherwise the request may be ignored.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Requirements
      description: List your requirements. This will help us [write tests for the example](https://github.com/ariakit/ariakit/blob/main/contributing.md#testing-the-example).
      placeholder: |
        - The dialog should open when pressing the A key.
        - The dialog should close when pressing the B key.
